services:
#    catalog.example:
#        class: CatalogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    app.product_serializer:
        class: CatalogBundle\Service\ProductSerializer
        arguments: ["@doctrine.orm.entity_manager"]

    app.form.type.category:
        class: CatalogBundle\Form\Type\CategoryType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    app.form.type.edit_category:
        class: CatalogBundle\Form\Type\EditCategoryType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    app.form.type.product:
        class: CatalogBundle\Form\Type\ProductType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    app.category_menu_generator:
        class: CatalogBundle\Service\CategoryMenuGenerator
        arguments: ["@doctrine.orm.entity_manager"]

    app.category_paginator_generator:
        class: CatalogBundle\Service\PaginatorGenerator
        arguments: ["@doctrine.orm.entity_manager"]

    app.product_generator:
        class: CatalogBundle\Service\ProductGenerator
        arguments: ["@doctrine.orm.entity_manager"]

    app.category_generator:
        class: CatalogBundle\Service\CategoryGenerator
        arguments: ["@doctrine.orm.entity_manager"]