product_edit:
    path:     /{id}/edit
    defaults: { _controller: "CatalogBundle:Product:editProduct" }
    methods:  [GET, POST]

product_crud:
    path:     /crud
    defaults: { _controller: "CatalogBundle:Product:gridProducts" }
    methods:  GET

product_create:
    path:     /create
    defaults: { _controller: "CatalogBundle:Product:createProduct" }
    methods:  [GET, POST]

product_remove:
    path:     /{id}/remove
    defaults: { _controller: "CatalogBundle:Product:removeProduct" }
    methods:  [GET, POST]

product_ajax:
    path:     /ajax
    defaults: { _controller: "CatalogBundle:Product:getProductsAjax" }

product_count:
    path:     /ajax/count
    defaults: { _controller: "CatalogBundle:Product:getCount" }

product_by_id:
    path:     /{id}
    defaults: { _controller: "CatalogBundle:Product:getProductById" }
    methods:  GET